In [1]:
import numpy as np
import pandas as pd

/home/gopi/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies.rename(columns={'id':'movie_id'},inplace=True)

In [6]:
movies.head(1)

,budget,genres,homepage,movie_id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [7]:
movies = movies.merge(credits,on='movie_id')

In [8]:
movies.shape

(4803, 23)

In [9]:
movies.info

<bound method DataFrame.info of          budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
...         ...                                                ...
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801          0                                                 []
4802          0                [{"id": 99, "name": "Documentary"}]

                                               homepage  movie_id  \
0                           http://www.avatarmovie.com/     19995
1          http://disney.go.com/disneypictures/pirates/       285
2           http://www.sonypictures.com/movies/spectre/    206647
3                    http://www.thedarkknightrises.com/     49026
4                  http://movies.disney.com/john-carter     49529
...                                                 ...       ...
4798                                                NaN      9367
4799                                                NaN     72766
4800  http://www.hallmarkchannel.com/signedsealeddel...    231617
4801                        http://shanghaicalling.com/    126186
4802                                                NaN     25975

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en
4     [{"id": 818, "name": "based on novel"}, {"id":...                en
...                                                 ...               ...
4798  [{"id": 5616, "name": "united states\u2013mexi...                es
4799                                                 []                en
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en
4801                                                 []                en
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en

                                original_title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577
1     Captain Barbossa, long believed to be dead, ha...  139.082615
2     A cryptic message from Bond’s past sends him o...  107.376788
3     Following the death of District Attorney Harve...  112.312950
4     John Carter is a war-weary, former military ca...   43.926995
...                                                 ...         ...
4798  El Mariachi just wants to play his guitar and ...   14.269792
4799  A newlywed couple's honeymoon is upended by th...    0.642552
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476
4801  When ambitious New York attorney Sam is sent t...    0.857008
4802  Ever since the second grade when he first saw ...    1.929883

                                   production_companies  ... runtime  \
0     [{"name": "Ingenious Film Partners", "id": 289...  ...   162.0
1     [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   169.0
2     [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   148.0
3     [{"name": "Legendary Pictures", "id": 923}, {"...  ...   165.0
4           [{"name": "Walt Disney Pictures", "id": 2}]  ...   132.0
...                                                 ...  ...     ...
4798           [{"name": "Columbia Pictures", "id": 5}]  ...    81.0
4799                                                 []  ...    85.0
4800  [{"name": "Front Street Pictures", "id": 3958}...  ...   120.0
4801                                                 []  ...    98.0
4802  [{"name": "rusty bear entertainment", "id": 87...  ...    90.0

                                       spoken_languages    status  \
0     [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1              [{"iso_639_1": "en", "name": "English"}]  Released
2     [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3              [{"iso_639_1": "en", "name": "English"}]  Released
4              [{"iso_639_1": "en", "name": "English"}]  Released
...                                                 ...       ...
4798      [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released
4799                                                 []  Released
4800           [{"iso_639_1": "en", "name": "English"}]  Released
4801           [{"iso_639_1": "en", "name": "English"}]  Released
4802           [{"iso_639_1": "en", "name": "English"}]  Released

                                                tagline  \
0                           Enter the World of Pandora.
1        At the end of the world, the adventure begins.
2                                 A Plan No One Escapes
3                                       The Legend Ends
4                  Lost in our world, found in another.
...                                                 ...
4798  He didn't come looking for trouble, but troubl...
4799  A newlywed couple's honeymoon is upended by th...
4800                                                NaN
4801                           A New Yorker in Shanghai
4802                                                NaN

                                       title_x vote_average vote_count  \
0                                       Avatar          7.2      11800
1     Pirates of the Caribbean: At World's End          6.9       4500
2                                      Spectre          6.3       4466
3                        The Dark Knight Rises          7.6       9106
4                                  John Carter          6.1       2124
...                                        ...          ...        ...
4798                               El Mariachi          6.6        238
4799                                 Newlyweds          5.9          5
4800                 Signed, Sealed, Delivered          7.0          6
4801                          Shanghai Calling          5.7          7
4802                         My Date with Drew          6.3         16

                                       title_y  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4798                               El Mariachi
4799                                 Newlyweds
4800                 Signed, Sealed, Delivered
4801                          Shanghai Calling
4802                         My Date with Drew

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...
1     [{"cast_id": 4, "character": "Captain Jack Spa...
2     [{"cast_id": 1, "character": "James Bond", "cr...
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4     [{"cast_id": 5, "character": "John Carter", "c...
...                                                 ...
4798  [{"cast_id": 1, "character": "El Mariachi", "c...
4799  [{"cast_id": 1, "character": "Buzzy", "credit_...
4800  [{"cast_id": 8, "character": "Oliver O\u2019To...
4801  [{"cast_id": 3, "character": "Sam", "credit_id...
4802  [{"cast_id": 3, "character": "Herself", "credi...

                                                   crew
0     [{"credit_id": "52fe48009251416c750aca23", "de...
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     [{"credit_id": "54805967c3a36829b5002c41", "de...
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...                                                 ...
4798  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4799  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4800  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4801  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4802  [{"credit_id": "58ce021b9251415a390165d9", "de...

[4803 rows x 23 columns]>

In [8]:
#Columns I am considering for model trailing are movie_id,genres,keywords,title,overview,status,cast,crew and vote_average

movies = movies[['movie_id','genres','keywords','title_x','overview','status','vote_average','cast','crew']]

In [11]:
movies.head()

,movie_id,genres,keywords,title_x,overview,status,vote_average,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
movies.head()

,movie_id,genres,keywords,title_x,overview,status,vote_average,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.rename(columns={'title_x':'title'},inplace=True)
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
# For converting string to List

import ast

In [12]:
movies.dropna(inplace=True)

In [20]:
# For fetching keywords from List of object

def fetchKeywords(obj):
    toReturn = []
    for data in ast.literal_eval(obj):
            toReturn.append(data['name'])
    return toReturn

In [14]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
movies['genres'] = movies['genres'].apply(fetchKeywords)

In [19]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
movies.loc[:, 'keywords'] = movies['keywords'].apply(fetchKeywords)

In [22]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
#movies.rename(columns={'title_x':'title'},inplace=True)

In [28]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
movies.cast=movies['cast'].apply(fetchKeywords)

In [24]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [31]:
def pickTopActors(cast):
    counter=0
    toReturn=[]
    for actor in cast:
        if counter!=5:
            toReturn.append(actor)
            counter+=1
        else:
            break
    cast=toReturn
    return cast

In [33]:
# movies['cast'] = movies['cast'].apply(pickTopActors)
movies['cast'][0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez']

In [24]:
def fetch_director(crew):
    toReturn = []
    for data in ast.literal_eval(crew):
        if data['job']=='Director':
            toReturn.append(data['name'])
    return toReturn

In [25]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [36]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...",Released,7.2,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Released,6.9,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,Released,6.3,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,Released,7.6,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...",Released,6.1,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [26]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [38]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",Released,7.2,"[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",Released,6.9,"[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...",Released,6.3,"[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",Released,7.6,"[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...",Released,6.1,"[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [27]:
def transformText(Obj):
    toReturn=[]
    for text in Obj:
        text=text.replace(" ","")
        text=text.lower()
        if text!="":
           toReturn.append(text)
    return toReturn

In [28]:
movies['cast'] = movies['cast'].apply(transformText)
movies['crew'] = movies['crew'].apply(transformText)
movies['overview'] = movies['overview'].apply(transformText)
movies['keywords'] = movies['keywords'].apply(transformText)

In [58]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[in, the, 22nd, century,, a, paraplegic, marin...",Released,7.2,"[samworthington, zoesaldana, sigourneyweaver, ...",[jamescameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[captain, barbossa,, long, believed, to, be, d...",Released,6.9,"[johnnydepp, orlandobloom, keiraknightley, ste...",[goreverbinski]
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[a, cryptic, message, from, bond’s, past, send...",Released,6.3,"[danielcraig, christophwaltz, léaseydoux, ralp...",[sammendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[following, the, death, of, district, attorney...",Released,7.6,"[christianbale, michaelcaine, garyoldman, anne...",[christophernolan]
4,49529,"[Action, Adventure, Science Fiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[john, carter, is, a, war-weary,, former, mili...",Released,6.1,"[taylorkitsch, lynncollins, samanthamorton, wi...",[andrewstanton]

In [41]:
movies['genres'][0]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [29]:
movies['genres'] = movies['genres'].apply(transformText)

In [43]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew
0,19995,"[action, adventure, fantasy, sciencefiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[in, the, 22nd, century,, a, paraplegic, marin...",Released,7.2,"[samworthington, zoesaldana, sigourneyweaver, ...",[jamescameron]
1,285,"[adventure, fantasy, action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[captain, barbossa,, long, believed, to, be, d...",Released,6.9,"[johnnydepp, orlandobloom, keiraknightley, ste...",[goreverbinski]
2,206647,"[action, adventure, crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[a, cryptic, message, from, bond’s, past, send...",Released,6.3,"[danielcraig, christophwaltz, léaseydoux, ralp...",[sammendes]
3,49026,"[action, crime, drama, thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[following, the, death, of, district, attorney...",Released,7.6,"[christianbale, michaelcaine, garyoldman, anne...",[christophernolan]
4,49529,"[action, adventure, sciencefiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[john, carter, is, a, war-weary,, former, mili...",Released,6.1,"[taylorkitsch, lynncollins, samanthamorton, wi...",[andrewstanton]

In [30]:
movies['tags'] = movies['genres']+movies['keywords']+movies['cast']+movies['crew']+movies['overview']

In [45]:
movies.head()

,movie_id,genres,keywords,title,overview,status,vote_average,cast,crew,tags
0,19995,"[action, adventure, fantasy, sciencefiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[in, the, 22nd, century,, a, paraplegic, marin...",Released,7.2,"[samworthington, zoesaldana, sigourneyweaver, ...",[jamescameron],"[action, adventure, fantasy, sciencefiction, c..."
1,285,"[adventure, fantasy, action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[captain, barbossa,, long, believed, to, be, d...",Released,6.9,"[johnnydepp, orlandobloom, keiraknightley, ste...",[goreverbinski],"[adventure, fantasy, action, ocean, drugabuse,..."
2,206647,"[action, adventure, crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[a, cryptic, message, from, bond’s, past, send...",Released,6.3,"[danielcraig, christophwaltz, léaseydoux, ralp...",[sammendes],"[action, adventure, crime, spy, basedonnovel, ..."
3,49026,"[action, crime, drama, thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[following, the, death, of, district, attorney...",Released,7.6,"[christianbale, michaelcaine, garyoldman, anne...",[christophernolan],"[action, crime, drama, thriller, dccomics, cri..."
4,49529,"[action, adventure, sciencefiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[john, carter, is, a, war-weary,, former, mili...",Released,6.1,"[taylorkitsch, lynncollins, samanthamorton, wi...",[andrewstanton],"[action, adventure, sciencefiction, basedonnov..."

In [31]:
dataFinal = movies[['movie_id','title','tags','status','vote_average']]

In [47]:
dataFinal.head()

,movie_id,title,tags,status,vote_average
0,19995,Avatar,"[action, adventure, fantasy, sciencefiction, c...",Released,7.2
1,285,Pirates of the Caribbean: At World's End,"[adventure, fantasy, action, ocean, drugabuse,...",Released,6.9
2,206647,Spectre,"[action, adventure, crime, spy, basedonnovel, ...",Released,6.3
3,49026,The Dark Knight Rises,"[action, crime, drama, thriller, dccomics, cri...",Released,7.6
4,49529,John Carter,"[action, adventure, sciencefiction, basedonnov...",Released,6.1

In [32]:
dataFinal['tags'] = dataFinal['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_4793/3994657891.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFinal['tags'] = dataFinal['tags'].apply(lambda x:" ".join(x))

In [49]:
dataFinal.head()

,movie_id,title,tags,status,vote_average
0,19995,Avatar,action adventure fantasy sciencefiction cultur...,Released,7.2
1,285,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drugabuse exoti...,Released,6.9
2,206647,Spectre,action adventure crime spy basedonnovel secret...,Released,6.3
3,49026,The Dark Knight Rises,action crime drama thriller dccomics crimefigh...,Released,7.6
4,49529,John Carter,action adventure sciencefiction basedonnovel m...,Released,6.1

In [81]:
dataFinal.head()
dataFinal.to_csv('Preprocessed_Movie_Data.csv',index=False)

In [51]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from nltk) (7.0)
Collecting joblib (from nltk)
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2023.12.25-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 375.3 kB/s eta 0:00:00 kB/s eta 0:00:01
Collecting tqdm (from nltk)
  Downloading tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 389.6 kB/s eta 0:00:001m408.5 kB/s eta 0:00:01
Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 337.6 kB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading regex-2023.12.25-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (777 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 777.0/777.0 kB 287.2 kB/s eta 0:00:00[36m0:00:01m eta 0:00:01
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 365.1 kB/s eta 0:00:00[36m0:00:01[36m0:00:01:01
Downloading tqdm-4.66.2-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 373.7 kB/s eta 0:00:00 kB/s eta 0:00:01:01
Installing collected packages: tqdm, regex, joblib, nltk
Successfully installed joblib-1.3.2 nltk-3.8.1 regex-2023.12.25 tqdm-4.66.2

In [34]:
import nltk

In [35]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [36]:
def stemText(text):
    toReturn =[]
    for word in text.split():
        toReturn.append(ps.stem(word))
    return " ".join(toReturn)

In [37]:
dataFinal['tags'] = dataFinal['tags'].apply(stemText)

/tmp/ipykernel_4793/2367265816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataFinal['tags'] = dataFinal['tags'].apply(stemText)

In [61]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /usr/lib/python3/dist-packages (from scikit-learn) (1.17.4)
Collecting scipy>=1.5.0 (from scikit-learn)
  Downloading scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.9/58.9 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: joblib>=1.1.1 in /home/gopi/.local/lib/python3.8/site-packages (from scikit-learn) (1.3.2)
Collecting threadpoolctl>=2.0.0 (from scikit-learn)
  Downloading threadpoolctl-3.3.0-py3-none-any.whl.metadata (13 kB)
Collecting numpy<2.0,>=1.17.3 (from scikit-learn)
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Downloading scikit_learn-1.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 13.2 MB/s eta 0:00:00m eta 0:00:010:01:01
Downloading scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 13.1 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 12.0 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Downloading threadpoolctl-3.3.0-py3-none-any.whl (17 kB)
Installing collected packages: threadpoolctl, numpy, scipy, scikit-learn
Successfully installed numpy-1.24.4 scikit-learn-1.3.2 scipy-1.10.1 threadpoolctl-3.3.0

In [62]:
from sklearn.feature_extraction.text import CountVectorizer

In [65]:
cv = CountVectorizer(max_features=7000,stop_words='english')

In [67]:
movieVector = cv.fit_transform(dataFinal['tags']).toarray()

In [138]:
import pickle
fileObject = open('movieRelation.pkl', 'wb')
pickle.dump(movieRelations,fileObject)

In [69]:
movieVector.shape

(4800, 7000)

In [75]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoëkravitz'],
      dtype=object)

In [76]:
from sklearn.metrics.pairwise import cosine_similarity

In [78]:
movieRelations = cosine_similarity(movieVector)

In [79]:
movieRelations

array([[1.        , 0.07435224, 0.07644708, ..., 0.0418121 , 0.        ,
        0.        ],
       [0.07435224, 1.        , 0.055577  , ..., 0.02279804, 0.        ,
        0.02423931],
       [0.07644708, 0.055577  , 1.        , ..., 0.02344036, 0.        ,
        0.        ],
       ...,
       [0.0418121 , 0.02279804, 0.02344036, ..., 1.        , 0.03883678,
        0.04089304],
       [0.        , 0.        , 0.        , ..., 0.03883678, 1.        ,
        0.08258401],
       [0.        , 0.02423931, 0.        , ..., 0.04089304, 0.08258401,
        1.        ]])

In [94]:
sorted(list(enumerate(movieRelations[0])),reverse=True,key=lambda x:x[1])

[(0, 0.9999999999999994),
 (2403, 0.2533201985524494),
 (1213, 0.2528249484237158),
 (3723, 0.23596995186213474),
 (507, 0.23162743094465488),
 (539, 0.22613350843332272),
 (582, 0.223606797749979),
 (1201, 0.2111001654603745),
 (778, 0.20906050250177274),
 (4041, 0.20353605946582753),
 (61, 0.20309059861498083),
 (1191, 0.19943100880436643),
 (2780, 0.1926686588971131),
 (1914, 0.1918806447200494),
 (2327, 0.18815445225159544),
 (3603, 0.18698939800169145),
 (322, 0.1860968420796942),
 (1086, 0.18540496217739155),
 (4185, 0.18463723646899916),
 (74, 0.1846372364689991),
 (972, 0.18098069149825674),
 (260, 0.17837651700316892),
 (1438, 0.1776672636296754),
 (47, 0.17766726362967536),
 (151, 0.1773937187967248),
 (172, 0.1773937187967248),
 (3667, 0.175919798853417),
 (2966, 0.17524990930819542),
 (4399, 0.17407765595569785),
 (305, 0.17372057320849116),
 (942, 0.17056057308448835),
 (4, 0.1688801323682996),
 (2994, 0.16854996561581054),
 (495, 0.1679677532867563),
 (1326, 0.1679677532867563),
 (577, 0.16685595311797868),
 (83, 0.16566307331251645),
 (1198, 0.1651445647689541),
 (3322, 0.16448792373994225),
 (27, 0.16333965194414124),
 (94, 0.16245910832216473),
 (3992, 0.16245910832216473),
 (220, 0.1599005372667078),
 (168, 0.15909090909090912),
 (184, 0.15909090909090912),
 (4330, 0.1590909090909091),
 (1272, 0.15745916432444343),
 (1068, 0.15731330124142318),
 (1318, 0.15717365336548286),
 (36, 0.1555939785660355),
 (3533, 0.15559397856603546),
 (300, 0.15392982399673988),
 (931, 0.15289415743128765),
 (2198, 0.15231794896123563),
 (1825, 0.1523179489612356),
 (91, 0.15075567228888181),
 (373, 0.15075567228888181),
 (661, 0.15075567228888181),
 (1352, 0.1492405014489273),
 (838, 0.148039131365948),
 (56, 0.14782809899727067),
 (529, 0.14777011582226215),
 (595, 0.14777011582226215),
 (41, 0.14634235175124088),
 (342, 0.14546434136292807),
 (2725, 0.14506471329641488),
 (1175, 0.14484136487558028),
 (150, 0.1446354779699756),
 (3157, 0.14414999403128945),
 (1531, 0.1436067394758882),
 (1976, 0.14301938838683886),
 (4003, 0.1421338109037403),
 (67, 0.13957263155977065),
 (149, 0.13926212476455826),
 (26, 0.13794014696151086),
 (1341, 0.13794014696151086),
 (31, 0.13762047064079508),
 (2069, 0.13762047064079508),
 (2509, 0.13762047064079508),
 (187, 0.13636363636363638),
 (581, 0.1353825902684706),
 (2754, 0.135116001384382),
 (513, 0.13483997249264842),
 (7, 0.13336626734231613),
 (111, 0.13336626734231613),
 (1377, 0.13336626734231613),
 (1932, 0.13336626734231613),
 (127, 0.13238067846429905),
 (52, 0.13193984914006274),
 (108, 0.13193984914006274),
 (311, 0.13193984914006274),
 (294, 0.13121597027036952),
 (1473, 0.13089257860118403),
 (275, 0.1292719224987548),
 (579, 0.1292719224987548),
 (3404, 0.1292719224987548),
 (3774, 0.128564869306645),
 (466, 0.12856486930664499),
 (1482, 0.12856486930664499),
 (1294, 0.12792042981336627),
 (568, 0.12741179785940637),
 (2490, 0.12741179785940637),
 (3349, 0.12741179785940637),
 (1390, 0.12704195151210984),
 (1053, 0.1266600992762247),
 (1324, 0.1257389226923863),
 (3975, 0.1257389226923863),
 (2163, 0.1256297269074015),
 (4532, 0.1254363015010636),
 (17, 0.12436708454077278),
 (1959, 0.12436708454077278),
 (95, 0.12424730498438732),
 (46, 0.12392039927415242),
 (843, 0.12392039927415242),
 (490, 0.12309149097933275),
 (777, 0.12309149097933272),
 (859, 0.12227899701112963),
 (1554, 0.12227899701112963),
 (4072, 0.12227899701112963),
 (4342, 0.12087344460380704),
 (502, 0.12087344460380703),
 (2127, 0.12087344460380703),
 (461, 0.1207011373963169),
 (1939, 0.1207011373963169),
 (505, 0.12060453783110546),
 (935, 0.12060453783110546),
 (2578, 0.12060453783110546),
 (413, 0.11918282365569904),
 (2680, 0.11918282365569904),
 (1270, 0.11877113736973438),
 (249, 0.11826247919781653),
 (773, 0.11826247919781653),
 (2372, 0.11826247919781653),
 (2867, 0.11776030079682895),
 (72, 0.11772040233700279),
 (126, 0.11631052629980887),
 (138, 0.11631052629980887),
 (3623, 0.11631052629980887),
 (3617, 0.11631052629980886),
 (368, 0.1160517706371319),
 (476, 0.1160517706371319),
 (487, 0.1160517706371319),
 (1319, 0.11583309365626165),
 (14, 0.11495012246792571),
 (2175, 0.11495012246792571),
 (2444, 0.11495012246792571),
 (4223, 0.11495012246792571),
 (158, 0.11487593716012254),
 (134, 0.11396057645963795),
 (668, 0.11396057645963795),
 (1367, 0.11396057645963795),
 (166, 0.11236664374387369),
 (1012, 0.11236664374387369),
 (1872, 0.11219363880101488),
 (208, 0.11197850219117086),
 (1093, 0.11197850219117086),
 (1768, 0.11197850219117086),
 (2646, 0.11197850219117086),
 (102, 0.11134044285378081),
 (1735, 0.11134044285378081),
 (754, 0.11113855611859677),
 (1083, 0.11113855611859677),
 (68, 0.11009637651263605),
 (483, 0.11009637651263605),
 (1044, 0.11009637651263605),
 (1271, 0.11009637651263605),
 (1827, 0.11009637651263605),
 (2965, 0.11009637651263605),
 (438, 0.10994987428338562),
 (1296, 0.10994987428338562),
 (1395, 0.10994987428338562),
 (84, 0.1096908636190696),
 (1709, 0.1096908636190696),
 (2474, 0.1096908636190696),
 (3078, 0.1096908636190696),
 (369, 0.10879853497231116),
 (1802, 0.10879853497231115),
 (678, 0.10830607221477648),
 (1001, 0.10830607221477648),
 (1155, 0.10830607221477648),
 (1652, 0.10830607221477648),
 (3371, 0.10830607221477648),
 (3729, 0.10830607221477648),
 (549, 0.107682623063487),
 (900, 0.107682623063487),
 (937, 0.107682623063487),
 (999, 0.10734844004467699),
 (589, 0.10660035817780524),
 (160, 0.10660035817780522),
 (870, 0.10660035817780522),
 (1667, 0.10660035817780522),
 (2668, 0.10660035817780522),
 (2783, 0.10660035817780522),
 (3230, 0.10660035817780522),
 (781, 0.10660035817780521),
 (1298, 0.10660035817780521),
 (3207, 0.10594836210330251),
 (2278, 0.10555008273018725),
 (85, 0.10552897060221728),
 (122, 0.10497277621629561),
 (4667, 0.10497277621629561),
 (278, 0.10453025125088636),
 (557, 0.10453025125088636),
 (1412, 0.10453025125088636),
 (1611, 0.10453025125088636),
 (139, 0.1044465935734187),
 (2325, 0.1037571695799112),
 (1491, 0.10375716957991118),
 (454, 0.10353942082032278),
 (232, 0.10341753799900383),
 (422, 0.10341753799900383),
 (3142, 0.10308121991160743),
 (889, 0.10298573010888745),
 (182, 0.10257624248277727),
 (536, 0.10257624248277727),
 (2054, 0.1019294382875251),
 (2735, 0.1019294382875251),
 (4462, 0.1019294382875251),
 (43, 0.10163945352271772),
 (1217, 0.10163945352271772),
 (2541, 0.10163945352271772),
 (1568, 0.10112997936948633),
 (1345, 0.10112997936948631),
 (2366, 0.10072787050317253),
 (3625, 0.10072787050317253),
 (50, 0.10050378152592121),
 (121, 0.10050378152592121),
 (449, 0.10050378152592121),
 (1028, 0.10050378152592121),
 (3493, 0.10050378152592121),
 (238, 0.10050378152592118),
 (432, 0.09984038297885897),
 (3088, 0.09984038297885897),
 (206, 0.09971550440218321),
 (81, 0.09928550884822428),
 (307, 0.09927330486454493),
 (87, 0.09913631941932194),
 (236, 0.09913631941932194),
 (3135, 0.09913631941932194),
 (123, 0.09897594780811197),
 (420, 0.09897594780811197),
 (692, 0.09897594780811197),
 (1506, 0.09897594780811197),
 (627, 0.09869275424396534),
 (808, 0.09869275424396534),
 (3714, 0.09869275424396534),
 (3993, 0.09869275424396534),
 (5, 0.09813358399735746),
 (228, 0.09813358399735746),
 (3304, 0.09813358399735746),
 (21, 0.0978231976089037),
 (28, 0.0978231976089037),
 (295, 0.0978231976089037),
 (786, 0.0978231976089037),
 (1610, 0.0978231976089037),
 (3003, 0.0978231976089037),
 (3423, 0.0978231976089037),
 (740, 0.09731236802019037),
 (939, 0.09697622757528537),
 (3335, 0.09656090991705352),
 (170, 0.09651142956027287),
 (572, 0.09651142956027287),
 (189, 0.09642365197998373),
 (653, 0.09642365197998373),
 (1518, 0.09642365197998373),
 (1569, 0.09642365197998373),
 (2628, 0.09642365197998373),
 (262, 0.09572994763343545),
 (1449, 0.09572994763343545),
 (332, 0.09534625892455924),
 (3629, 0.09534625892455924),
 (4771, 0.09534625892455924),
 (229, 0.09534625892455922),
 (541, 0.09496714704969828),
 (1490, 0.09496714704969828),
 (1495, 0.09430419201928972),
 (2756, 0.09430419201928972),
 (4128, 0.09430419201928972),
 (467, 0.09422229518055114),
 (2492, 0.09422229518055114),
 (3436, 0.09422229518055114),
 (75, 0.09417632186960223),
 (131, 0.09417632186960223),
 (223, 0.09417632186960223),
 (472, 0.09417632186960223),
 (1234, 0.09417632186960223),
 (2811, 0.09417632186960223),
 (3147, 0.09417632186960223),
 (654, 0.09349469900084573),
 (2100, 0.09349469900084573),
 (687, 0.09304842103984709),
 (1765, 0.09304842103984709),
 (3748, 0.09304842103984709),
 (233, 0.09231861823449956),
 (1739, 0.09231861823449956),
 (2515, 0.09231861823449956),
 (3050, 0.09231861823449956),
 (3616, 0.09231861823449956),
 (3655, 0.09231861823449956),
 (3832, 0.09231861823449956),
 (4484, 0.09231861823449956),
 (2433, 0.09208868358546966),
 (1034, 0.09196009797434057),
 (1608, 0.09196009797434057),
 (174, 0.09090909090909091),
 (643, 0.09090909090909091),
 (1291, 0.09090909090909091),
 (2241, 0.09090909090909091),
 (2247, 0.09090909090909091),
 (3928, 0.09090909090909091),
 (4090, 0.09090909090909091),
 (1433, 0.09074425108007847),
 (200, 0.09045340337332909),
 (256, 0.09045340337332909),
 (1878, 0.09045340337332909),
 (2317, 0.09045340337332909),
 (1399, 0.09009374626955591),
 (207, 0.08989331499509895),
 (330, 0.08989331499509895),
 (445, 0.08989331499509895),
 (1817, 0.08989331499509895),
 (2142, 0.08989331499509895),
 (3776, 0.08989331499509895),
 (3867, 0.08989331499509895),
 (1769, 0.08945703337056415),
 (2093, 0.08945703337056415),
 (10, 0.08891084489487741),
 (371, 0.08891084489487741),
 (480, 0.08891084489487741),
 (508, 0.08891084489487741),
 (510, 0.08891084489487741),
 (535, 0.08891084489487741),
 (1079, 0.08891084489487741),
 (1106, 0.08891084489487741),
 (1192, 0.08891084489487741),
 (3615, 0.08891084489487741),
 (363, 0.0888336318148377),
 (105, 0.0886968593983624),
 (157, 0.0886968593983624),
 (319, 0.0886968593983624),
 (624, 0.0886968593983624),
 (1074, 0.0886968593983624),
 (1163, 0.0886968593983624),
 (1277, 0.0886968593983624),
 (1936, 0.0886968593983624),
 (2155, 0.0886968593983624),
 (3947, 0.0886968593983624),
 (4011, 0.0886968593983624),
 (4466, 0.0886968593983624),
 (266, 0.0879598994267085),
 (334, 0.0879598994267085),
 (2066, 0.0879598994267085),
 (4539, 0.0876249546540977),
 (33, 0.08703882797784893),
 (312, 0.08703882797784893),
 (715, 0.08703882797784893),
 (791, 0.08703882797784893),
 (878, 0.08703882797784893),
 (898, 0.08703882797784893),
 (985, 0.08703882797784893),
 (1153, 0.08703882797784893),
 (1680, 0.08703882797784893),
 (2235, 0.08703882797784893),
 (2556, 0.08703882797784893),
 (2639, 0.08703882797784893),
 (2781, 0.08703882797784893),
 (3532, 0.08703882797784893),
 (3713, 0.08703882797784893),
 (4191, 0.08703882797784893),
 (4196, 0.08703882797784893),
 (4249, 0.08703882797784893),
 (4325, 0.08703882797784893),
 (18, 0.08703882797784891),
 (9, 0.0861460984507896),
 (410, 0.0861460984507896),
 (2550, 0.0861460984507896),
 (2644, 0.0861460984507896),
 (35, 0.08547043234472845),
 (263, 0.08547043234472845),
 (362, 0.08547043234472845),
 (2047, 0.08547043234472845),
 (2450, 0.08547043234472845),
 (4397, 0.08547043234472845),
 (412, 0.08528028654224418),
 (587, 0.08528028654224418),
 (1686, 0.08528028654224418),
 (1695, 0.08528028654224418),
 (491, 0.0848066914440948),
 (11, 0.0844400661841498),
 (814, 0.0844400661841498),
 (1840, 0.0844400661841498),
 (1990, 0.0844400661841498),
 (2482, 0.0844400661841498),
 (2586, 0.0844400661841498),
 (2814, 0.0844400661841498),
 (3402, 0.0844400661841498),
 (239, 0.08427498280790527),
 (244, 0.08398387664337814),
 (325, 0.08398387664337814),
 (660, 0.08398387664337814),
 (920, 0.08398387664337814),
 (1715, 0.08398387664337814),
 (1721, 0.08398387664337814),
 (785, 0.08375315127160099),
 (799, 0.08375315127160099),
 (602, 0.08362420100070908),
 (1440, 0.08362420100070908),
 (4347, 0.08362420100070908),
 (301, 0.08324089477650336),
 (2564, 0.08324089477650336),
 (243, 0.08283153665625823),
 (279, 0.08283153665625823),
 (813, 0.08283153665625823),
 (1354, 0.08283153665625823),
 (3874, 0.08283153665625823),
 (148, 0.08257228238447704),
 (511, 0.08257228238447704),
 (1303, 0.08257228238447704),
 (1474, 0.08257228238447704),
 (2087, 0.08257228238447704),
 (2952, 0.08257228238447704),
 (230, 0.08224396186997113),
 (473, 0.08206099398622183),
 (596, 0.08206099398622183),
 (994, 0.08131156281817417),
 (1230, 0.08131156281817417),
 (1900, 0.08131156281817417),
 (2707, 0.08131156281817417),
 (3384, 0.08131156281817417),
 (3548, 0.08131156281817417),
 (2109, 0.0812820110952944),
 (88, 0.08122955416108235),
 (389, 0.08122955416108235),
 (977, 0.08122955416108235),
 (1567, 0.08122955416108235),
 (1750, 0.08122955416108235),
 (2245, 0.08122955416108235),
 (3317, 0.08122955416108235),
 (479, 0.08081352297940449),
 (270, 0.08058229640253803),
 (671, 0.08058229640253803),
 (1273, 0.08058229640253803),
 (3438, 0.08058229640253803),
 (3457, 0.08058229640253803),
 (4337, 0.08058229640253803),
 (4510, 0.08058229640253803),
 (219, 0.0799502686333539),
 (356, 0.0799502686333539),
 (564, 0.0799502686333539),
 (1024, 0.0799502686333539),
 (1246, 0.0799502686333539),
 (1256, 0.0799502686333539),
 (2654, 0.0799502686333539),
 (2862, 0.0799502686333539),
 (3130, 0.0799502686333539),
 (169, 0.07987230638308718),
 (331, 0.07987230638308718),
 (752, 0.07987230638308718),
 (2103, 0.07918075824648958),
 (2357, 0.07918075824648958),
 (3551, 0.07918075824648958),
 (141, 0.0787295821622217),
 (457, 0.0787295821622217),
 (1468, 0.0787295821622217),
 (1580, 0.0787295821622217),
 (2645, 0.0787295821622217),
 (3443, 0.0787295821622217),
 (1826, 0.07850686719788597),
 (2734, 0.07850686719788597),
 (2442, 0.0781631749350903),
 (129, 0.0778498944161523),
 (143, 0.0778498944161523),
 (827, 0.0778498944161523),
 (1016, 0.0778498944161523),
 (3213, 0.0778498944161523),
 (4581, 0.0778498944161523),
 (4731, 0.0778498944161523),
 (12, 0.07756315349925287),
 (167, 0.07756315349925287),
 (292, 0.07756315349925287),
 (1139, 0.07756315349925287),
 (1372, 0.07756315349925287),
 (2390, 0.07756315349925287),
 (4748, 0.07756315349925287),
 (32, 0.07720914364821829),
 (199, 0.07720914364821829),
 (217, 0.07720914364821829),
 (234, 0.07720914364821829),
 (618, 0.07720914364821829),
 (48, 0.07658395810674837),
 (1633, 0.07658395810674837),
 (1094, 0.07644707871564384),
 (2, 0.07644707871564382),
 (23, 0.07644707871564382),
 (745, 0.07644707871564382),
 (960, 0.07644707871564382),
 (2655, 0.07644707871564382),
 (3296, 0.07644707871564382),
 (3444, 0.07644707871564382),
 (4554, 0.07644707871564382),
 (1302, 0.07597371763975862),
 (274, 0.07576538541439333),
 (315, 0.07537783614444091),
 (403, 0.07537783614444091),
 (534, 0.07537783614444091),
 (1199, 0.07537783614444091),
 (1524, 0.07537783614444091),
 (1743, 0.07537783614444091),
 (2161, 0.07537783614444091),
 (2871, 0.07537783614444091),
 (2874, 0.07537783614444091),
 (2963, 0.07537783614444091),
 (3522, 0.07537783614444091),
 (3919, 0.07537783614444091),
 (4496, 0.07537783614444091),
 (4635, 0.07537783614444091),
 (4648, 0.07537783614444091),
 (4651, 0.07537783614444091),
 (190, 0.07479575920067658),
 (812, 0.07479575920067658),
 (1777, 0.07479575920067658),
 (1, 0.07435223956449145),
 (1204, 0.07435223956449145),
 (1583, 0.07435223956449145),
 (2298, 0.07435223956449145),
 (2859, 0.07435223956449145),
 (3465, 0.07435223956449145),
 (3809, 0.07435223956449145),
 (19, 0.07422696190252054),
 (45, 0.07422696190252054),
 (2348, 0.07422696190252054),
 (3898, 0.07422696190252054),
 (2197, 0.07367094686837573),
 (152, 0.07336739820667779),
 (203, 0.07336739820667779),
 (306, 0.07336739820667779),
 (341, 0.07336739820667779),
 (626, 0.07336739820667779),
 (894, 0.07336739820667779),
 (1077, 0.07336739820667779),
 (1266, 0.07336739820667779),
 (1513, 0.07336739820667779),
 (1682, 0.07336739820667779),
 (1741, 0.07336739820667779),
 (1922, 0.07336739820667779),
 (3228, 0.07336739820667779),
 (4620, 0.07336739820667779),
 (486, 0.07321342658217783),
 (2380, 0.07321342658217783),
 (63, 0.07312724241271307),
 (381, 0.07312724241271307),
 (866, 0.07312724241271307),
 (2790, 0.07312724241271307),
 (2850, 0.07312724241271307),
 (3175, 0.07312724241271307),
 (3971, 0.07312724241271307),
 (4562, 0.07312724241271307),
 (501, 0.07259540086406277),
 (1528, 0.07259540086406277),
 (1892, 0.07259540086406277),
 (142, 0.07242068243779014),
 (227, 0.07242068243779014),
 (245, 0.07242068243779014),
 (2122, 0.07242068243779014),
 (2229, 0.07242068243779014),
 (2577, 0.07242068243779014),
 (2677, 0.07242068243779014),
 (4310, 0.07242068243779014),
 (193, 0.07219887278223847),
 (153, 0.07207499701564472),
 (2786, 0.07207499701564472),
 (4500, 0.07207499701564472),
 (222, 0.07156562669645132),
 (37, 0.07150969419341943),
 (39, 0.07150969419341943),
 (547, 0.07150969419341943),
 (775, 0.07150969419341943),
 (901, 0.07150969419341943),
 (922, 0.07150969419341943),
 (2933, 0.07150969419341943),
 (3023, 0.07150969419341943),
 (38, 0.07106690545187015),
 (1658, 0.07106690545187015),
 (1692, 0.07106690545187015),
 (1822, 0.07106690545187015),
 (1918, 0.07106690545187015),
 (2268, 0.07106690545187015),
 (2333, 0.07106690545187015),
 (4273, 0.07106690545187015),
 (4486, 0.07106690545187015),
 (16, 0.07063224140220167),
 (164, 0.07063224140220167),
 (242, 0.07063224140220167),
 (400, 0.07063224140220167),
 (492, 0.07063224140220167),
 (787, 0.07063224140220167),
 (1146, 0.07063224140220167),
 (2213, 0.07063224140220167),
 (2443, 0.07063224140220167),
 (2638, 0.07063224140220167),
 (3097, 0.07063224140220167),
 (3757, 0.07063224140220167),
 (4618, 0.07063224140220167),
 (1920, 0.07057846732405855),
 (3555, 0.07057846732405855),
 (103, 0.07009996372327816),
 (125, 0.06978631577988532),
 (96, 0.06978631577988531),
 (112, 0.06978631577988531),
 (241, 0.06978631577988531),
 (329, 0.06978631577988531),
 (632, 0.06978631577988531),
 (854, 0.06978631577988531),
 (1158, 0.06978631577988531),
 (1290, 0.06978631577988531),
 (1322, 0.06978631577988531),
 (3844, 0.06978631577988531),
 (4335, 0.06978631577988531),
 (4552, 0.06978631577988531),
 (246, 0.06963106238227913),
 (286, 0.06963106238227913),
 (1653, 0.06963106238227913),
 (3326, 0.06939092270667112),
 (776, 0.06917144638660747),
 (850, 0.06917144638660747),
 (1002, 0.06917144638660747),
 (1251, 0.06917144638660747),
 (1279, 0.06917144638660747),
 (1999, 0.06917144638660747),
 (2665, 0.06917144638660747),
 (3112, 0.06917144638660747),
 (3721, 0.06917144638660747),
 (3825, 0.06917144638660747),
 (4004, 0.06917144638660747),
 (4467, 0.06917144638660747),
 (70, 0.06897007348075543),
 (101, 0.06897007348075543),
 (402, 0.06897007348075543),
 (794, 0.06897007348075543),
 (899, 0.06897007348075543),
 (1110, 0.06897007348075543),
 (1286, 0.06897007348075543),
 (3086, 0.06897007348075543),
 (3159, 0.06897007348075543),
 (4261, 0.06897007348075543),
 (1984, 0.06872081327440495),
 (40, 0.06818181818181818),
 (235, 0.06818181818181818),
 (349, 0.06818181818181818),
 (361, 0.06818181818181818),
 (737, 0.06818181818181818),
 (1067, 0.06818181818181818),
 (1287, 0.06818181818181818),
 (1517, 0.06818181818181818),
 (2157, 0.06818181818181818),
 (2289, 0.06818181818181818),
 (3694, 0.06818181818181818),
 (62, 0.06741998624632421),
 (210, 0.06741998624632421),
 (365, 0.06741998624632421),
 (584, 0.06741998624632421),
 (680, 0.06741998624632421),
 (1320, 0.06741998624632421),
 (1361, 0.06741998624632421),
 (1481, 0.06741998624632421),
 (1764, 0.06741998624632421),
 (2050, 0.06741998624632421),
 (2983, 0.06741998624632421),
 (3064, 0.06741998624632421),
 (3067, 0.06741998624632421),
 (3280, 0.06741998624632421),
 (3426, 0.06741998624632421),
 (4198, 0.06741998624632421),
 (4406, 0.06741998624632421),
 (4425, 0.06741998624632421),
 (51, 0.0670025210172808),
 (82, 0.06668313367115805),
 (98, 0.06668313367115805),
 (540, 0.06668313367115805),
 (634, 0.06668313367115805),
 (833, 0.06668313367115805),
 (908, 0.06668313367115805),
 (3798, 0.06668313367115805),

In [128]:
def RecommendMovie(movieName):
    movie_index = dataFinal[dataFinal['title']==movieName]

    if movie_index.shape[0]==0:
        return "Oops!!! Either you entered movie name incorrectly or maybe it is not avialable in our database, sorry! Please enter another movie"
    
    movie_index = movie_index.index[0]
    distances = movieRelations[movie_index]
    distances = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    toReturn = []
    for recommended in distances:
        movieNow = dataFinal.iloc[recommended[0]].title
        toReturn.append(movieNow)

    return toReturn

In [136]:
RecommendMovie('Harry Porter')
# dataFinal.iloc[0].title

['Ghost Ship',
 'The Notebook',
 'Under the Same Moon',
 'The Bounty',
 'Pirates of the Caribbean: On Stranger Tides']

In [124]:
returnedData = dataFinal[dataFinal['title']=='Hello']

In [127]:
returnedData.shape[0]

0

In [146]:
temp = pd.DataFrame(movieVector)
temp
pickle.dump(temp,open('vector.pkl','wb'))

In [148]:
temp1 = pd.DataFrame(movieRelations)
pickle.dump(temp1,open('similarities.pkl','wb'))
temp1

,0,1,2,3,4,5,6,7,8,9,...,4790,4791,4792,4793,4794,4795,4796,4797,4798,4799
0,1.000000,0.074352,0.076447,0.064282,0.168880,0.098134,0.035050,0.133366,0.050965,0.086146,...,0.000000,0.000000,0.037987,0.047088,0.000000,0.017645,0.043519,0.041812,0.000000,0.000000
1,0.074352,1.000000,0.055577,0.035050,0.069061,0.107015,0.019111,0.121197,0.055577,0.093942,...,0.000000,0.000000,0.020712,0.025675,0.000000,0.038483,0.000000,0.022798,0.000000,0.024239
2,0.076447,0.055577,1.000000,0.054056,0.071007,0.066018,0.019649,0.124611,0.057143,0.096589,...,0.079682,0.000000,0.000000,0.000000,0.016737,0.039567,0.000000,0.023440,0.000000,0.000000
3,0.064282,0.035050,0.054056,1.000000,0.029854,0.055513,0.049568,0.062869,0.036037,0.182743,...,0.025126,0.025126,0.053722,0.049945,0.021110,0.062383,0.000000,0.029566,0.044781,0.078587
4,0.168880,0.069061,0.071007,0.029854,1.000000,0.109381,0.048834,0.185814,0.071007,0.100020,...,0.033005,0.000000,0.070567,0.021869,0.138648,0.147501,0.000000,0.019418,0.078431,0.041292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,0.017645,0.038483,0.039567,0.062383,0.147501,0.076187,0.027212,0.138054,0.118701,0.033440,...,0.000000,0.055174,0.132712,0.054836,0.254954,1.000000,0.000000,0.000000,0.147501,0.120797
4796,0.043519,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.068041,0.000000,0.000000,0.028583,0.000000,1.000000,0.120096,0.000000,0.000000
4797,0.041812,0.022798,0.023440,0.029566,0.019418,0.018054,0.000000,0.000000,0.046881,0.019811,...,0.065372,0.032686,0.017471,0.043315,0.013731,0.000000,0.120096,1.000000,0.038837,0.040893
4798,0.000000,0.000000,0.000000,0.044781,0.078431,0.054690,0.032556,0.041292,0.094676,0.020004,...,0.000000,0.033005,0.088209,0.000000,0.138648,0.147501,0.000000,0.038837,1.000000,0.082584
4799,0.000000,0.024239,0.000000,0.078587,0.041292,0.038391,0.000000,0.043478,0.099689,0.021063,...,0.000000,0.000000,0.037152,0.023027,0.072995,0.120797,0.000000,0.040893,0.082584,1.000000

In [147]:
temp

,0,1,2,3,4,5,6,7,8,9,...,6990,6991,6992,6993,6994,6995,6996,6997,6998,6999
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4796,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4797,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4798,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4799,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# After completing preprocessing and computing similarities between movies I stated working on frontend using streamlit.